# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.103.0"

default_platform :android

platform :android do
  before_all do
     ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task:"test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"

  lane :beta do
  
	#emulator for Android
    avd_name:"Test-Run-Emulator-API23",
    target_id:"Google Inc.:Google APIs:23",
    avd_abi:"google_apis/x86_64",
    gradle_task:"app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.pp.anhle.helloworld.HelloTest",

  
	#gradle(task: "app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.pp.anhle.helloworld.HelloTest", properties: {'versionCode' => 1})
	gradle(task: "testDebug", properties: {'versionCode' => 1})
    gradle(task: "assembleRelease", properties: {'versionCode' => 1})
    

    crashlytics(
       groups: "ci-test",
       api_token: "d241e3297a82297479a8c29751465eea577f9772",
       build_secret: "104c0cae8d45fe16fa0b74bc56b1fad37713b18519530213aae8a7cbd7cb389a"
    )

    desc "Deploy a new version to the Google Play"
    lane :deploy do
    gradle(task: "assembleRelease")
    supply
    end

    slack(
      message: "Android New Development Build available for download :rocket:",
      success: true,
      channel: "#continuous-deployment",
      payload: {
        'Last Commit Message' => last_git_commit[:message],
        'Author' => last_git_commit[:author]
      },
      default_payloads: []
    )
  end
  error do |lane, exception|

    slack(message: exception.to_s, success: false)
    notify("Lane #{lane} failed to complete.")

  end
end

  

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
